<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\MainCategory;
use App\Models\Product;
use App\Models\Stock;
use App\Models\SubCategory;
use App\Models\Supplier;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // -------------------------------------------------------
        // Resolve lookup maps (slug => id)
        // -------------------------------------------------------
        $brand = fn(string $slug): int => Brand::where('slug', Str::slug($slug))->value('id');

        $mainCat = fn(string $slug): int => MainCategory::where('slug', $slug)->value('id');

        $subCat = fn(string $slug): int => SubCategory::where('slug', $slug)->value('id');

        $supplier = fn(string $email): int => Supplier::where('email', $email)->value('id');
        $mobileHub   = $supplier('sales@mobilesparehub.com');
        $laptopWorld  = $supplier('contact@laptoppartsworld.com');
        $rajeshElec  = $supplier('rajesh@rajeshelectronics.com');
        $globalTech  = $supplier('global@globaltech.com');


        // -------------------------------------------------------
        // Product definitions
        // -------------------------------------------------------
        $products = [

            // ---- LAPTOP MOTHERBOARDS -------------------------------------------
            [
                'name'                 => 'Asus VivoBook 15 Motherboard',
                'slug'                 => 'asus-vivobook-15-motherboard',
                'code'                 => 'MB-ASU-VB15',
                'barcode'              => 'MB-ASU-VB15',
                'brand_id'             => $brand('Asus'),
                'main_category_id'     => $mainCat('LAPTOP-MB'),
                'sub_category_id'      => $subCat('ASUS-MB'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_laptop_mb.jpg',
                'purchase_price'       => 4500,
                'selling_price'        => 6500,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 3,
                'short_description'    => 'Original replacement motherboard for Asus VivoBook 15',
                'full_description'     => 'Genuine OEM motherboard compatible with Asus VivoBook 15 series laptops.',
                'status'               => 'active',
                'manufacturer'         => 'Asus',
                'model_number'         => 'VivoBook 15',
                'part_number'          => 'MB-ASU-VB15',
                'warranty'             => '6 Months',
                'color'                => 'Green PCB',
                'weight'               => '350g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 12,
            ],
            [
                'name'                 => 'Dell Inspiron 15 Motherboard',
                'slug'                 => 'dell-inspiron-15-motherboard',
                'code'                 => 'MB-DEL-INS15',
                'barcode'              => 'MB-DEL-INS15',
                'brand_id'             => $brand('Dell'),
                'main_category_id'     => $mainCat('LAPTOP-MB'),
                'sub_category_id'      => $subCat('DELL-MB'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_laptop_mb.jpg',
                'purchase_price'       => 5000,
                'selling_price'        => 7200,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 3,
                'short_description'    => 'Replacement motherboard for Dell Inspiron 15',
                'full_description'     => 'Genuine Dell motherboard for Inspiron 15 3000/5000 series.',
                'status'               => 'active',
                'manufacturer'         => 'Dell',
                'model_number'         => 'Inspiron 15',
                'part_number'          => 'MB-DEL-INS15',
                'warranty'             => '6 Months',
                'color'                => 'Green PCB',
                'weight'               => '380g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 10,
            ],

            [
                'name'                 => 'HP Pavilion 14 Motherboard',
                'slug'                 => 'hp-pavilion-14-motherboard',
                'code'                 => 'MB-HP-PAV14',
                'barcode'              => 'MB-HP-PAV14',
                'brand_id'             => $brand('HP'),
                'main_category_id'     => $mainCat('LAPTOP-MB'),
                'sub_category_id'      => $subCat('HP-MB'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_laptop_mb.jpg',
                'purchase_price'       => 4200,
                'selling_price'        => 6000,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 3,
                'short_description'    => 'Replacement motherboard for HP Pavilion 14',
                'full_description'     => 'OEM motherboard compatible with HP Pavilion 14 series.',
                'status'               => 'active',
                'manufacturer'         => 'HP',
                'model_number'         => 'Pavilion 14',
                'part_number'          => 'MB-HP-PAV14',
                'warranty'             => '6 Months',
                'color'                => 'Green PCB',
                'weight'               => '340g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 11,
            ],
            [
                'name'                 => 'Lenovo IdeaPad 3 Motherboard',
                'slug'                 => 'lenovo-ideapad-3-motherboard',
                'code'                 => 'MB-LEN-IP3',
                'barcode'              => 'MB-LEN-IP3',
                'brand_id'             => $brand('Lenovo'),
                'main_category_id'     => $mainCat('LAPTOP-MB'),
                'sub_category_id'      => $subCat('LENOVO-MB'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_laptop_mb.jpg',
                'purchase_price'       => 4800,
                'selling_price'        => 6800,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 3,
                'short_description'    => 'Replacement motherboard for Lenovo IdeaPad 3',
                'full_description'     => 'Compatible OEM motherboard for Lenovo IdeaPad 3 series.',
                'status'               => 'active',
                'manufacturer'         => 'Lenovo',
                'model_number'         => 'IdeaPad 3',
                'part_number'          => 'MB-LEN-IP3',
                'warranty'             => '6 Months',
                'color'                => 'Green PCB',
                'weight'               => '360g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 15,
            ],
            [
                'name'                 => 'Asus TUF F15 Motherboard',
                'slug'                 => 'asus-tuf-f15-motherboard',
                'code'                 => 'MB-ASU-TUFF15',
                'barcode'              => 'MB-ASU-TUFF15',
                'brand_id'             => $brand('Asus'),
                'main_category_id'     => $mainCat('LAPTOP-MB'),
                'sub_category_id'      => $subCat('ASUS-MB'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_laptop_mb.jpg',
                'purchase_price'       => 7500,
                'selling_price'        => 10500,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 2,
                'short_description'    => 'Replacement motherboard for Asus TUF Gaming F15',
                'full_description'     => 'High-performance OEM motherboard for Asus TUF Gaming F15 series.',
                'status'               => 'active',
                'manufacturer'         => 'Asus',
                'model_number'         => 'TUF F15',
                'part_number'          => 'MB-ASU-TUFF15',
                'warranty'             => '6 Months',
                'color'                => 'Green PCB',
                'weight'               => '400g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 10,
            ],

            // ---- MOBILE MOTHERBOARDS -------------------------------------------
            [
                'name'                 => 'Samsung Galaxy A53 Motherboard',
                'slug'                 => 'samsung-galaxy-a53-motherboard',
                'code'                 => 'MMB-SAM-A53',
                'barcode'              => 'MMB-SAM-A53',
                'brand_id'             => $brand('Samsung'),
                'main_category_id'     => $mainCat('MOBILE-MB'),
                'sub_category_id'      => $subCat('SAMSUNG-MOBILE-MB'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_mobile_mb.jpg',
                'purchase_price'       => 3200,
                'selling_price'        => 4800,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 5,
                'short_description'    => 'Original replacement motherboard for Samsung Galaxy A53',
                'full_description'     => 'Genuine OEM logic board for Samsung Galaxy A53 5G.',
                'status'               => 'active',
                'manufacturer'         => 'Samsung',
                'model_number'         => 'Galaxy A53',
                'part_number'          => 'MMB-SAM-A53',
                'warranty'             => '3 Months',
                'color'                => 'Black PCB',
                'weight'               => '120g',
                'country_of_origin'    => 'South Korea',
                'stock_quantity'       => 25,
            ],
            [
                'name'                 => 'Xiaomi Redmi Note 12 Motherboard',
                'slug'                 => 'xiaomi-redmi-note-12-motherboard',
                'code'                 => 'MMB-XIA-RN12',
                'barcode'              => 'MMB-XIA-RN12',
                'brand_id'             => $brand('Xiaomi'),
                'main_category_id'     => $mainCat('MOBILE-MB'),
                'sub_category_id'      => $subCat('XIAOMI-MOBILE-MB'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_mobile_mb.jpg',
                'purchase_price'       => 2800,
                'selling_price'        => 4200,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 5,
                'short_description'    => 'Replacement motherboard for Xiaomi Redmi Note 12',
                'full_description'     => 'Compatible OEM motherboard for Xiaomi Redmi Note 12 series.',
                'status'               => 'active',
                'manufacturer'         => 'Xiaomi',
                'model_number'         => 'Redmi Note 12',
                'part_number'          => 'MMB-XIA-RN12',
                'warranty'             => '3 Months',
                'color'                => 'Black PCB',
                'weight'               => '110g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 30,
            ],
            [
                'name'                 => 'OnePlus Nord CE3 Motherboard',
                'slug'                 => 'oneplus-nord-ce3-motherboard',
                'code'                 => 'MMB-OP-NCE3',
                'barcode'              => 'MMB-OP-NCE3',
                'brand_id'             => $brand('OnePlus'),
                'main_category_id'     => $mainCat('MOBILE-MB'),
                'sub_category_id'      => $subCat('ONEPLUS-MOBILE-MB'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_mobile_mb.jpg',
                'purchase_price'       => 3500,
                'selling_price'        => 5200,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 5,
                'short_description'    => 'Replacement motherboard for OnePlus Nord CE3',
                'full_description'     => 'Genuine OEM logic board for OnePlus Nord CE3.',
                'status'               => 'active',
                'manufacturer'         => 'OnePlus',
                'model_number'         => 'Nord CE3',
                'part_number'          => 'MMB-OP-NCE3',
                'warranty'             => '3 Months',
                'color'                => 'Black PCB',
                'weight'               => '115g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 22,
            ],

            [
                'name'                 => 'Realme 11 Pro Motherboard',
                'slug'                 => 'realme-11-pro-motherboard',
                'code'                 => 'MMB-REA-11P',
                'barcode'              => 'MMB-REA-11P',
                'brand_id'             => $brand('Realme'),
                'main_category_id'     => $mainCat('MOBILE-MB'),
                'sub_category_id'      => $subCat('REALME-MOBILE-MB'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_mobile_mb.jpg',
                'purchase_price'       => 2500,
                'selling_price'        => 3800,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 5,
                'short_description'    => 'Replacement motherboard for Realme 11 Pro',
                'full_description'     => 'Compatible OEM motherboard for Realme 11 Pro.',
                'status'               => 'active',
                'manufacturer'         => 'Realme',
                'model_number'         => 'Realme 11 Pro',
                'part_number'          => 'MMB-REA-11P',
                'warranty'             => '3 Months',
                'color'                => 'Black PCB',
                'weight'               => '108g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 28,
            ],
            [
                'name'                 => 'Oppo A78 Motherboard',
                'slug'                 => 'oppo-a78-motherboard',
                'code'                 => 'MMB-OPP-A78',
                'barcode'              => 'MMB-OPP-A78',
                'brand_id'             => $brand('Oppo'),
                'main_category_id'     => $mainCat('MOBILE-MB'),
                'sub_category_id'      => $subCat('OPPO-MOBILE-MB'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_mobile_mb.jpg',
                'purchase_price'       => 2200,
                'selling_price'        => 3500,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 5,
                'short_description'    => 'Replacement motherboard for Oppo A78',
                'full_description'     => 'Compatible OEM logic board for Oppo A78.',
                'status'               => 'active',
                'manufacturer'         => 'Oppo',
                'model_number'         => 'Oppo A78',
                'part_number'          => 'MMB-OPP-A78',
                'warranty'             => '3 Months',
                'color'                => 'Black PCB',
                'weight'               => '105g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 20,
            ],

            // ---- DISPLAYS -------------------------------------------------------
            [
                'name'                 => 'Samsung A53 AMOLED Display',
                'slug'                 => 'samsung-a53-amoled-display',
                'code'                 => 'DSP-SAM-A53',
                'barcode'              => 'DSP-SAM-A53',
                'brand_id'             => $brand('Samsung'),
                'main_category_id'     => $mainCat('DISPLAY'),
                'sub_category_id'      => $subCat('MOBILE-DISPLAY'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_display_mobile.jpg',
                'purchase_price'       => 2800,
                'selling_price'        => 4200,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 5,
                'short_description'    => 'AMOLED display assembly for Samsung Galaxy A53',
                'full_description'     => 'Original AMOLED display with touch digitizer for Samsung Galaxy A53 5G.',
                'status'               => 'active',
                'manufacturer'         => 'Samsung',
                'model_number'         => 'Galaxy A53',
                'part_number'          => 'DSP-SAM-A53',
                'warranty'             => '3 Months',
                'color'                => 'Black',
                'weight'               => '90g',
                'country_of_origin'    => 'South Korea',
                'stock_quantity'       => 20,
            ],

            [
                'name'                 => 'iPhone 13 OLED Display',
                'slug'                 => 'iphone-13-oled-display',
                'code'                 => 'DSP-APL-IP13',
                'barcode'              => 'DSP-APL-IP13',
                'brand_id'             => $brand('Apple'),
                'main_category_id'     => $mainCat('DISPLAY'),
                'sub_category_id'      => $subCat('MOBILE-DISPLAY'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_display_mobile.jpg',
                'purchase_price'       => 5500,
                'selling_price'        => 8500,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 3,
                'short_description'    => 'OLED display assembly for Apple iPhone 13',
                'full_description'     => 'High-quality OLED display with touch digitizer for Apple iPhone 13.',
                'status'               => 'active',
                'manufacturer'         => 'Apple',
                'model_number'         => 'iPhone 13',
                'part_number'          => 'DSP-APL-IP13',
                'warranty'             => '3 Months',
                'color'                => 'Black',
                'weight'               => '80g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 15,
            ],
            [
                'name'                 => 'Redmi Note 12 LCD Display',
                'slug'                 => 'redmi-note-12-lcd-display',
                'code'                 => 'DSP-XIA-RN12',
                'barcode'              => 'DSP-XIA-RN12',
                'brand_id'             => $brand('Xiaomi'),
                'main_category_id'     => $mainCat('DISPLAY'),
                'sub_category_id'      => $subCat('MOBILE-DISPLAY'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_display_mobile.jpg',
                'purchase_price'       => 1800,
                'selling_price'        => 2800,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 5,
                'short_description'    => 'LCD display assembly for Xiaomi Redmi Note 12',
                'full_description'     => 'Compatible LCD display with touch digitizer for Redmi Note 12.',
                'status'               => 'active',
                'manufacturer'         => 'Xiaomi',
                'model_number'         => 'Redmi Note 12',
                'part_number'          => 'DSP-XIA-RN12',
                'warranty'             => '3 Months',
                'color'                => 'Black',
                'weight'               => '85g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 25,
            ],
            [
                'name'                 => 'Dell Inspiron 15 FHD Display',
                'slug'                 => 'dell-inspiron-15-fhd-display',
                'code'                 => 'DSP-DEL-INS15',
                'barcode'              => 'DSP-DEL-INS15',
                'brand_id'             => $brand('Dell'),
                'main_category_id'     => $mainCat('DISPLAY'),
                'sub_category_id'      => $subCat('LAPTOP-DISPLAY'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_display_laptop.jpg',
                'purchase_price'       => 3500,
                'selling_price'        => 5200,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 3,
                'short_description'    => '15.6-inch FHD display panel for Dell Inspiron 15',
                'full_description'     => 'Original 15.6" FHD IPS display panel for Dell Inspiron 15 series.',
                'status'               => 'active',
                'manufacturer'         => 'Dell',
                'model_number'         => 'Inspiron 15',
                'part_number'          => 'DSP-DEL-INS15',
                'warranty'             => '6 Months',
                'color'                => 'Silver Bezel',
                'weight'               => '350g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 18,
            ],
            [
                'name'                 => 'HP Pavilion 15 Display Panel',
                'slug'                 => 'hp-pavilion-15-display-panel',
                'code'                 => 'DSP-HP-PAV15',
                'barcode'              => 'DSP-HP-PAV15',
                'brand_id'             => $brand('HP'),
                'main_category_id'     => $mainCat('DISPLAY'),
                'sub_category_id'      => $subCat('LAPTOP-DISPLAY'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_display_laptop.jpg',
                'purchase_price'       => 3200,
                'selling_price'        => 4800,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 3,
                'short_description'    => '15.6-inch FHD display panel for HP Pavilion 15',
                'full_description'     => 'Compatible 15.6" FHD display panel for HP Pavilion 15 series.',
                'status'               => 'active',
                'manufacturer'         => 'HP',
                'model_number'         => 'Pavilion 15',
                'part_number'          => 'DSP-HP-PAV15',
                'warranty'             => '6 Months',
                'color'                => 'Black Bezel',
                'weight'               => '340g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 15,
            ],

            // ---- ACCESSORIES ----------------------------------------------------
            [
                'name'                 => 'Type-C Fast Charging Cable 1m',
                'slug'                 => 'type-c-fast-charging-cable-1m',
                'code'                 => 'ACC-USB-TYPEC',
                'barcode'              => 'ACC-USB-TYPEC',
                'brand_id'             => $brand('Generic'),
                'main_category_id'     => $mainCat('ACCESSORIES-ITEM'),
                'sub_category_id'      => $subCat('USB-CABLES'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_cable_usb.jpg',
                'purchase_price'       => 80,
                'selling_price'        => 150,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 20,
                'short_description'    => 'Braided USB Type-C fast charging cable 1 metre',
                'full_description'     => 'Durable braided 3A fast charging Type-C cable, 1 metre length.',
                'status'               => 'active',
                'manufacturer'         => 'Generic',
                'model_number'         => 'USB-TC-1M',
                'part_number'          => 'ACC-USB-TYPEC',
                'warranty'             => '1 Month',
                'color'                => 'Black',
                'weight'               => '50g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 150,
            ],
            [
                'name'                 => 'Boat BassHeads 100 Earphones',
                'slug'                 => 'boat-bassheads-100-earphones',
                'code'                 => 'ACC-EAR-BOAT100',
                'barcode'              => 'ACC-EAR-BOAT100',
                'brand_id'             => $brand('Generic'),
                'main_category_id'     => $mainCat('ACCESSORIES-ITEM'),
                'sub_category_id'      => $subCat('EARPHONES'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_earphone.jpg',
                'purchase_price'       => 250,
                'selling_price'        => 450,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 15,
                'short_description'    => 'Boat BassHeads 100 wired earphones with mic',
                'full_description'     => 'Boat BassHeads 100 in-ear wired earphones with HD sound and microphone.',
                'status'               => 'active',
                'manufacturer'         => 'Boat',
                'model_number'         => 'BassHeads 100',
                'part_number'          => 'ACC-EAR-BOAT100',
                'warranty'             => '1 Year',
                'color'                => 'Black',
                'weight'               => '30g',
                'country_of_origin'    => 'India',
                'stock_quantity'       => 120,
            ],
            [
                'name'                 => 'Mi 20000mAh Power Bank',
                'slug'                 => 'mi-20000mah-power-bank',
                'code'                 => 'ACC-PB-MI20K',
                'barcode'              => 'ACC-PB-MI20K',
                'brand_id'             => $brand('Xiaomi'),
                'main_category_id'     => $mainCat('ACCESSORIES-ITEM'),
                'sub_category_id'      => $subCat('POWER-BANKS'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_powerbank.jpg',
                'purchase_price'       => 800,
                'selling_price'        => 1299,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 10,
                'short_description'    => 'Mi 20000mAh 18W fast charge power bank',
                'full_description'     => 'Xiaomi Mi 20000mAh power bank with 18W fast charging and dual USB output.',
                'status'               => 'active',
                'manufacturer'         => 'Xiaomi',
                'model_number'         => 'Mi PB20',
                'part_number'          => 'ACC-PB-MI20K',
                'warranty'             => '1 Year',
                'color'                => 'White',
                'weight'               => '440g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 100,
            ],

            [
                'name'                 => 'Tempered Glass Screen Guard',
                'slug'                 => 'tempered-glass-screen-guard',
                'code'                 => 'ACC-SG-TEMP',
                'barcode'              => 'ACC-SG-TEMP',
                'brand_id'             => $brand('Generic'),
                'main_category_id'     => $mainCat('ACCESSORIES-ITEM'),
                'sub_category_id'      => $subCat('SCREEN-GUARDS'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_tempered.jpg',
                'purchase_price'       => 40,
                'selling_price'        => 99,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 30,
                'short_description'    => '9H tempered glass screen protector (universal)',
                'full_description'     => 'Ultra-thin 9H hardness tempered glass screen guard, anti-fingerprint coating.',
                'status'               => 'active',
                'manufacturer'         => 'Generic',
                'model_number'         => 'TG-UNIV',
                'part_number'          => 'ACC-SG-TEMP',
                'warranty'             => 'No Warranty',
                'color'                => 'Clear',
                'weight'               => '15g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 200,
            ],
            [
                'name'                 => 'Silicone Phone Case Universal',
                'slug'                 => 'silicone-phone-case-universal',
                'code'                 => 'ACC-CASE-SIL',
                'barcode'              => 'ACC-CASE-SIL',
                'brand_id'             => $brand('Generic'),
                'main_category_id'     => $mainCat('ACCESSORIES-ITEM'),
                'sub_category_id'      => $subCat('PHONE-CASES'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_cover.jpg',
                'purchase_price'       => 60,
                'selling_price'        => 149,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 25,
                'short_description'    => 'Soft silicone back cover (universal fit)',
                'full_description'     => 'Flexible silicone phone case providing shock absorption and grip.',
                'status'               => 'active',
                'manufacturer'         => 'Generic',
                'model_number'         => 'SIL-CASE-UNIV',
                'part_number'          => 'ACC-CASE-SIL',
                'warranty'             => 'No Warranty',
                'color'                => 'Black',
                'weight'               => '30g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 180,
            ],

            // ---- COMPUTER HARDWARE ----------------------------------------------
            [
                'name'                 => 'Intel Core i5-12400 Processor',
                'slug'                 => 'intel-core-i5-12400-processor',
                'code'                 => 'CPU-INT-I512400',
                'barcode'              => 'CPU-INT-I512400',
                'brand_id'             => $brand('Intel'),
                'main_category_id'     => $mainCat('ELECTRONICE-ITEM'),
                'sub_category_id'      => $subCat('CPUS'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_ram.jpg',
                'purchase_price'       => 13500,
                'selling_price'        => 16500,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 2,
                'short_description'    => 'Intel Core i5-12400 12th Gen desktop processor LGA1700',
                'full_description'     => 'Intel Core i5-12400 6-core 12-thread processor, base 2.5GHz boost 4.4GHz, LGA1700 socket.',
                'status'               => 'active',
                'manufacturer'         => 'Intel',
                'model_number'         => 'Core i5-12400',
                'part_number'          => 'BX8071512400',
                'warranty'             => '3 Years',
                'color'                => 'N/A',
                'weight'               => '75g',
                'country_of_origin'    => 'Malaysia',
                'stock_quantity'       => 10,
            ],

            [
                'name'                 => 'Samsung 8GB DDR4 RAM 3200MHz',
                'slug'                 => 'samsung-8gb-ddr4-ram-3200mhz',
                'code'                 => 'RAM-SAM-8G3200',
                'barcode'              => 'RAM-SAM-8G3200',
                'brand_id'             => $brand('Samsung'),
                'main_category_id'     => $mainCat('ELECTRONICE-ITEM'),
                'sub_category_id'      => $subCat('RAM'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_ram.jpg',
                'purchase_price'       => 1800,
                'selling_price'        => 2499,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 5,
                'short_description'    => 'Samsung 8GB DDR4 3200MHz desktop RAM module',
                'full_description'     => 'Samsung 8GB DDR4 DIMM 3200MHz memory module for desktop PCs.',
                'status'               => 'active',
                'manufacturer'         => 'Samsung',
                'model_number'         => 'M378A1K43EB2',
                'part_number'          => 'RAM-SAM-8G3200',
                'warranty'             => 'Lifetime',
                'color'                => 'Green PCB',
                'weight'               => '40g',
                'country_of_origin'    => 'South Korea',
                'stock_quantity'       => 20,
            ],
            [
                'name'                 => 'Seagate 1TB SATA HDD',
                'slug'                 => 'seagate-1tb-sata-hdd',
                'code'                 => 'HDD-SEA-1TB',
                'barcode'              => 'HDD-SEA-1TB',
                'brand_id'             => $brand('Generic'),
                'main_category_id'     => $mainCat('ELECTRONICE-ITEM'),
                'sub_category_id'      => $subCat('HDD'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_ssd.jpg',
                'purchase_price'       => 2800,
                'selling_price'        => 3800,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 3,
                'short_description'    => 'Seagate Barracuda 1TB 3.5-inch SATA HDD 7200RPM',
                'full_description'     => 'Seagate Barracuda 1TB 3.5" SATA 6Gb/s 7200RPM hard drive, 256MB cache.',
                'status'               => 'active',
                'manufacturer'         => 'Seagate',
                'model_number'         => 'ST1000DM010',
                'part_number'          => 'HDD-SEA-1TB',
                'warranty'             => '2 Years',
                'color'                => 'Silver',
                'weight'               => '430g',
                'country_of_origin'    => 'China',
                'stock_quantity'       => 15,
            ],
            [
                'name'                 => 'Samsung 256GB SSD SATA',
                'slug'                 => 'samsung-256gb-ssd-sata',
                'code'                 => 'SSD-SAM-256G',
                'barcode'              => 'SSD-SAM-256G',
                'brand_id'             => $brand('Samsung'),
                'main_category_id'     => $mainCat('ELECTRONICE-ITEM'),
                'sub_category_id'      => $subCat('SSD'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_ssd.jpg',
                'purchase_price'       => 2200,
                'selling_price'        => 3200,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 3,
                'short_description'    => 'Samsung 870 EVO 256GB 2.5-inch SATA SSD',
                'full_description'     => 'Samsung 870 EVO 256GB SATA III 2.5" SSD, up to 560MB/s read speed.',
                'status'               => 'active',
                'manufacturer'         => 'Samsung',
                'model_number'         => 'MZ-77E250BW',
                'part_number'          => 'SSD-SAM-256G',
                'warranty'             => '5 Years',
                'color'                => 'Black',
                'weight'               => '55g',
                'country_of_origin'    => 'South Korea',
                'stock_quantity'       => 18,
            ],
            [
                'name'                 => 'AMD Radeon RX 6600 GPU',
                'slug'                 => 'amd-radeon-rx-6600-gpu',
                'code'                 => 'GPU-AMD-RX6600',
                'barcode'              => 'GPU-AMD-RX6600',
                'brand_id'             => $brand('AMD'),
                'main_category_id'     => $mainCat('ELECTRONICE-ITEM'),
                'sub_category_id'      => $subCat('GPU'),
                'unit_name'            => 'Piece',
                'unit_code'            => 'PCS',
                'image'                => 'seed_gpu.jpg',
                'purchase_price'       => 18000,
                'selling_price'        => 22500,
                'tax_percentage'       => 18,
                'discount_percentage'  => 0,
                'minimum_stock_alert'  => 2,
                'short_description'    => 'AMD Radeon RX 6600 8GB GDDR6 graphics card',
                'full_description'     => 'AMD Radeon RX 6600 8GB GDDR6, PCIe 4.0, ideal for 1080p gaming.',
                'status'               => 'active',
                'manufacturer'         => 'AMD',
                'model_number'         => 'RX 6600',
                'part_number'          => 'GPU-AMD-RX6600',
                'warranty'             => '3 Years',
                'color'                => 'Black',
                'weight'               => '700g',
                'country_of_origin'    => 'USA',
                'stock_quantity'       => 8,
            ],
        ];


        // -------------------------------------------------------
        // Insert products and their stock
        // -------------------------------------------------------
        foreach ($products as $data) {
            $stockQty = $data['stock_quantity'];
            unset($data['stock_quantity']);

            $product = Product::firstOrCreate(
                ['code' => $data['code']],
                $data
            );

            Stock::updateOrCreate(
                ['product_id' => $product->id],
                ['quantity'   => $stockQty]
            );
        }
    }
}
